package com.hbg.thefullenchilada.IAP;

public enum BillingResponseCodes {
	BILLING_RESPONSE_RESULT_OK,
	BILLING_RESPONSE_RESULT_USER_CANCELED,
	BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE,
	BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE,
	BILLING_RESPONSE_RESULT_ITEM_UNAVAILABLE,
	BILLING_RESPONSE_RESULT_DEVELOPER_ERROR,
	BILLING_RESPONSE_RESULT_ERROR,
	BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED,
	BILLING_RESPONSE_RESULT_ITEM_NOT_OWNED;
	
	public static BillingResponseCodes getCode(int val){
		return BillingResponseCodes.values()[val];
	}
}
